apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: cd-k8s
  namespace: flux-system
spec:
  interval: 1m
  ref:
    branch: main
  url: https://gitlab.com/longtien.5601/cd-k8s

---

apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cd-k8s
  namespace: flux-system
spec:
  interval: 3m
  path: ./dev
  prune: true
  retryInterval: 2m0s
  sourceRef:
    kind: GitRepository
    name: cd-k8s
  targetNamespace: default
  timeout: 3m0s
  wait: true
